permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Peiyu Sun
  email: sundev@126.com
  link: http://sundev.net
  github: http://github.com/sundev126

# 站点信息
title: Peiyu的博客 
description: Peiyu的博客
url: http://sundev.net
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/imgs/gavatar.png
favicon: /public/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-54888096-1
  url: sundev.net

# disqus 设置
disqus:
  shortname: suyan-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
